### ISSUE TITLE
Add j2 as extention

### ISSUE THREAD

**Issue by GElkayam** [wyattferguson/jinja2-kit-vscode#3]
Hi, 
I would like to use the plugin when editing Jinja2 templates for Ansible.
can it be configured?

**Comment by wyattferguson** [comment]
Yeah I could probably figure that out, Ansible uses .j2 files right?

**Comment by andyewing** [comment]
I'd love this feature too. I use Jinja2 with ansible and python rather than html.

**Comment by cyb3rw0lf** [comment]
same here would love to have .j2 extension
